### ISSUE TITLE
Can't use luaL_requiref with default luaopen_* functions

### ISSUE THREAD

**Issue by GrimMaple** [BindBC/bindbc-lua#10]
This code
```d
import bindbc.lua;

void main()
{
	LuaSupport lua = loadLua();
	auto L = luaL_newstate();
	luaL_requiref(L, "_G", luaopen_base, 0);
	lua_pop(L, 1);
	lua_close(L);
}
```
generates a compile-time error like this:
```
source/app.d(32,15): Error: function pointer `luaL_requiref(lua_State* L, const(char)* modname, int function(lua_State* L) nothrow openf, int glb)` is not callable using argument types `(lua_State*, string, extern (C) int function(lua_State* L) nothrow @nogc, int)`
source/app.d(32,15):        cannot pass argument `luaopen_base` of type `extern (C) int function(lua_State* L) nothrow @nogc` to parameter `int function(lua_State* L) nothrow openf`
/usr/bin/dmd failed with exit code 1.
```

I attempted to hack this by fiddling with `@nogc` at declarations, but it caused even more problems. I believe some better investigation is required

**Comment by mdparker** [comment]
`lua_requireref` takes a `lua_CFunction`. That's declared as `nothrow`. The failure is because `luaopen_base` is also `@nogc`.

Wow. This is tricky. As a rule of thumb in all my bindings, I declare function pointer types that are intended to represent function pointers in user code as `nothrow`, but not `@nogc`. I don't want to force `@nogc` on users, but `nothrow` makes sense for functions being called for C.

In this case, I didn't account for the fact that functions from the Lua C API can be arguments to these parameters. And of course, being from the C API, they are all `@nogc`.

So the question is what to do. If I make the function pointer type `@nogc`, then I will almost certainly break user code and will force all functions passed to Lua as a `lua_CFunction` to be `@nogc`. I suppose the only real solution to allow pointers to both `@nogc` functions and non-`@nogc` functions is to wrap the C function with two overloaded D functions and cast the `nothrow @nogc` pointer to `nothrow` before calling the C function.
